version: "3.9"

services:

  debug:
    build:
      context: .
      dockerfile: Dockerfile
    image: bizone-cve-debug
    container_name: bizone-cve-debug-container
    env_file:
      - ./config.debug.env
    volumes:
      - $PWD/logs:/app/logs
    restart: always
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -s -f -X POST http://localhost:7790/api/v1.0/status | grep True || exit 1" ]
#      start_period: 30s
#      interval: 30s
#      timeout: 10s
#      retries: 3

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: bizone-cve-debug
    container_name: bizone-cve-debug-container
    env_file:
      - ./config.debug.env
    volumes:
      - $PWD/logs:/app/logs
    restart: always
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -s -f -X POST http://localhost:7790/api/v1.0/status | grep True || exit 1" ]
#      start_period: 30s
#      interval: 30s
#      timeout: 10s
#      retries: 3

#  tests:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: bizone-cve-debug
#    container_name: bizone-cve-debug-container
#    env_file:
#      - ./config.debug.env
#    volumes:
#      - $PWD/logs:/app/logs
#    restart: always
##    healthcheck:
##      test: [ "CMD-SHELL", "curl -s -f -X POST http://localhost:7790/api/v1.0/status | grep True || exit 1" ]
##      start_period: 30s
##      interval: 30s
##      timeout: 10s
##      retries: 3

